apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  MINIO_ENDPOINT: minio-data-integration-datastore-api.apps.silver.devops.gov.bc.ca
  MINIO_ACCESS_KEY: routerdata
  MINIO_SECRET_KEY: routerdata@gov.bc.ca
  BC_API_KEY: HLaeSgzE3uDADUnOqVsuf73ZSFgpXAdV
