apiVersion: batch/v1
kind: Job
metadata:
  name: proximity-analysis-job-dev
spec:
  completions: 20                   # ✅The total number of chunks (chunk_01 to chunk_..)
  parallelism: 5                    # Run 5 pods in parallel
  completionMode: Indexed           # Enables JOB_INDEX injection to each pod
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: proximity-analysis
        image: image-registry.openshift-image-registry.svc:5000/dc318d-tools/proximity-analysis-dev
        env:
        - name: JOB_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_SECRET_KEY
        - name: BC_API_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: BC_API_KEY
        args:
        - "/tmp/workspace"                                    # $1: Workspace dir
        - "site_Hybrid_geocoder_joined_export_with_block_id.csv"  # $2: Original file name for reference
        - "FID"                                                # $3: Unique ID field in address file
        - "SITE_ALBERS_X"                                      # $4: X coordinate
        - "SITE_ALBERS_Y"                                      # $5: Y coordinate
        - "DISSEMINATION_BLOCK_ID"                             # $6: Admin ID
        - "GSR_SERVICE_BC_OFFICES_SVW.csv"                     # $7: Facility file
        - "OFFICE_NAM"                                         # $8: Facility ID field
        - "ALBERS_X"                                           # $9: Facility X
        - "ALBERS_Y"                                           # $10: Facility Y
        - "0.05"                                               # $11: Nearest % facilities to consider
        - "3005"                                               # $12: EPSG code
        - "$(BC_API_KEY)"                                      # $13: BC Route Planner API key
        - "servicebc"                                          # $14: Dataset tag